### ISSUE TITLE
No module named ddpm_edit 

### ISSUE THREAD

**Issue by hyperia-elliot** [timothybrooks/instruct-pix2pix#15]
I'm getting the following error when running the cli tool:

Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Global Step: 22000
Traceback (most recent call last):
  File "edit_cli.py", line 128, in <module>
    main()
  File "edit_cli.py", line 79, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_cli.py", line 52, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/ingest/ImageDiffuserService/proto/instruct2pix2pix/instruct-pix2pix/stable_diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/ingest/ImageDiffuserService/proto/instruct2pix2pix/instruct-pix2pix/stable_diffusion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/elliot/anaconda3/envs/pytorch-env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ldm.models.diffusion.ddpm_edit'

I've googled "ldm.models.diffusion.ddpm_edit" and don't see any references to this module existing.  any idea as to what i'm doing wrong?

**Comment by holynski** [comment]
Where are you running the script from (what is your shell's current directory)? The path includes are organized such that it's expected that the CLI will be called from the base directory (the directory containing the file `edit_cli.py` and `stable_diffusion` folder, since it adds a relative directory to the path). 

If you try running the command `python edit_cli.py` from within that folder, it should work. 

The ddpm_edit file is in our repo, under `stable_diffusion.ldm.models.diffusion.ddpm_edit`, but the `stable_diffusion` portion of that path is abstracted out by adding the stable_diffusion folder to the path --- this was done to avoid having to change all the paths within the original SD repository.

**Comment by hardyho** [comment]
Hi! Is the problem solved? I also got this problem and I am running `edit_cli.py` under the base folder. I Can't find any references with the name `ddpm_edit` too

**Comment by hardyho** [comment]
> Hi! Is the problem solved? I also got this problem and I am running `edit_cli.py` under the base folder. I Can't find any references with the name `ddpm_edit` too

Sorry, just solved the problem. Seems like it's a problem related to the environment. I was trying to use pip to install all packages manually from a previous environment and got the error. A new Conda environment won't have any problems.
