### ISSUE TITLE
Trying to run on a Mac with M1 Pro

### ISSUE THREAD

**Issue by metaphorz** [timothybrooks/instruct-pix2pix#20]
Is there a way to run this on Mac Silicon (M1 Pro 32GB?).  I tried the first conda command in your instructions, and it naturally returned with a cuda error. I will try now on Colab Pro, which uses nVidia cards and cuda.

**Comment by Kundanagrawalofficial** [comment]
Yes you need to install another package which is surely available there in GitHub

**Comment by metaphorz** [comment]
Yeah - unsure what the missing package is. Also, shouldn't torch.load use map_location="gpu" ?

**Comment by Kundanagrawalofficial** [comment]
There are other simple deep face program available in GitHub from using that GitHub files you will come around with file requirements.txt where library likes pytorch and others are mentions just download it and run on your pc so that all requirements related to libraries will be fullfil and then go with the flow

**Comment by metaphorz** [comment]
Can you suggest one that might work with this repo?

**Comment by holynski** [comment]
Hey, I'm not quite familiar enough with OSX Cuda support, so I wouldn't be able to tell you whether this will work or not. My expectation, though, is that you'll need a machine with a dedicated Nvidia GPU.

Regarding colab and requirements, this requirements.txt file should work:
https://huggingface.co/spaces/timbrooks/instruct-pix2pix/blob/main/requirements.txt

Closing for now, feel free to comment if you have more questions.

**Comment by metaphorz** [comment]
unfortunately the issue is not resolved. I installed requirements.txt as indicated, created a new run time and get this same error on Colab:

Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Traceback (most recent call last):
  File "edit_cli.py", line 128, in <module>
    main()
  File "edit_cli.py", line 79, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_cli.py", line 41, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by holynski** [comment]
Found a post online that suggests maybe the downloaded checkpoint is corrupted:

https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory

Can you try redownloading the checkpoint? Another thing you can do is verify that the checksum of the two files are the same.

**Comment by metaphorz** [comment]
I will retry: bash scripts/download_checkpoints.sh

**Comment by metaphorz** [comment]
It was a good suggestion. This time, the ckpt downloaded completely. However, another error arises:

Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Global Step: 22000
2023-01-22 05:26:37.495888: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in method __contains__ of dict object at 0x7f4b692e97c0> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "edit_cli.py", line 128, in <module>
    main()
  File "edit_cli.py", line 79, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_cli.py", line 52, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/content/drive/MyDrive/instruct-pix2pix/stable_diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/drive/MyDrive/instruct-pix2pix/stable_diffusion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/MyDrive/instruct-pix2pix/./stable_diffusion/ldm/models/diffusion/ddpm_edit.py", line 15, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/functional/__init__.py", line 68, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/functional/text/bert.py", line 28, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "/usr/local/lib/python3.8/dist-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.8/dist-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/generic.py", line 33, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: initialization failed

**Comment by metaphorz** [comment]
Maybe it is a numpy versioning error

**Comment by metaphorz** [comment]
I found this notebook on the web. It works: https://colab.research.google.com/drive/1spBkNSsIgaEvwr9JjAUKcPWy8ruxIwky?usp=sharing
