### ISSUE TITLE
Loading the model consistently fails

### ISSUE THREAD

**Issue by rwkeane** [timothybrooks/instruct-pix2pix#27]
Platform: Windows 10 x64 v22H2
Software: Python 3.8.5
Terminal: Anaconda Powershell Prompt v22.9.0

When running command: 
```
(ip2p) PS C:\Users\me\src\instruct-pix2pix> python edit_cli.py --input ..\..\Pictures\input.jpg --output ..\..\Pictures\modded.jpg --edit "turn him into a cyborg"
```

It receives the following error
```
Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Traceback (most recent call last):
  File "edit_cli.py", line 128, in <module>
    main()
  File "edit_cli.py", line 79, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_cli.py", line 41, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "C:\Users\Me\anaconda3\envs\ip2p\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Me\anaconda3\envs\ip2p\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Similarly, when running the following command: 
When running command: 
```
(ip2p) PS C:\Users\me\src\instruct-pix2pix> python edit_app.py
```

It receives the following error
```
Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Traceback (most recent call last):
  File "edit_app.py", line 268, in <module>
    main()
  File "edit_app.py", line 109, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_app.py", line 78, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "C:\Users\me\anaconda3\envs\ip2p\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\me\anaconda3\envs\ip2p\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by Kundanagrawalofficial** [comment]
When running command:

(ip2p) PS C:\Users\me\src\instruct-pix2pix> 


This error message is indicating that the file you are trying to load as a checkpoint (ckpt) is in a zip format, but the code is expecting it to be a file saved in PyTorch's native format. This could be caused by trying to load the wrong file or by the file being corrupted. You should check that the file path and name are correct and that the file is not corrupted. If the file is in a zip format, you will need to extract it before loading it.

**Comment by brycedrennan** [comment]
ckpt files are zip files. a partial or corrupted download is a good guess though

**Comment by rwkeane** [comment]
Corrupted download was my guess so I tried downloading the model via curl twice and had the same result
I'm wondering if there is something off in the Windows implementation of curl

Would anyone be willing to create a .torrent of the model?

**Comment by holynski** [comment]
My guess is also corrupted download. 

Where are you download from? Maybe try download via a browser instead of curl? You can access the file here:

https://huggingface.co/timbrooks/instruct-pix2pix/blob/main/instruct-pix2pix-00-22000.ckpt

**Comment by redcartel243** [comment]
I have been getting errors of all kinds for training the model but when it comes to using the pre-trained model to generate images just make sure all the packages are installed and all the files downloaded by download_checkpoints.sh and download_pretrained_sd.sh are in the right place(alternatively you can download them by yourself by opening them as a text file and following the commands). Also make sure that your version of Conda and torch are compatible
