### ISSUE TITLE
After create enviroment and running python edit_app.py get an error

### ISSUE THREAD

**Issue by venturaEffect** [timothybrooks/instruct-pix2pix#3]
Hi!
I get an error trying to make it work. I git cloned the repository, installed and created the enviroment and run python edit_app.py.

Got this error:

`Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Traceback (most recent call last):
  File "edit_app.py", line 268, in <module>
    main()
  File "edit_app.py", line 109, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_app.py", line 78, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/zaesarpo/anaconda3/envs/ip2p/lib/python3.8/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/zaesarpo/anaconda3/envs/ip2p/lib/python3.8/site-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
`
Any suggestions?

Appreciate

**Comment by holynski** [comment]
Looks like maybe you didn't download the checkpoint. 

Try running `bash scripts/download_checkpoints.sh` from the base directory.
