### ISSUE TITLE
ERROR: "ModuleNotFoundError: No module named 'torch.distributed.algorithms.model_averaging'"

### ISSUE THREAD

**Issue by celikmustafa89** [timothybrooks/instruct-pix2pix#33]
`Loading model from checkpoints/instruct-pix2pix-00-22000.ckpt
Global Step: 22000
Traceback (most recent call last):
  File "edit_cli.py", line 129, in <module>
    main()
  File "edit_cli.py", line 80, in main
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "edit_cli.py", line 53, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/stable_diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/stable_diffusion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/./stable_diffusion/ldm/models/diffusion/ddpm_edit.py", line 15, in <module>
    import pytorch_lightning as pl
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 50, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/trainer/__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 57, in <module>
    from pytorch_lightning.loops import PredictionLoop, TrainingEpochLoop
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch import TrainingBatchLoop  # noqa: F401
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/batch/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch.training_batch_loop import TrainingBatchLoop  # noqa: F401
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 20, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import _OUTPUTS_TYPE as _MANUAL_LOOP_OUTPUTS_TYPE
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import ManualOptimization  # noqa: F401
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 23, in <module>
    from pytorch_lightning.loops.utilities import _build_training_step_kwargs, _extract_hiddens
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 29, in <module>
    from pytorch_lightning.strategies.parallel import ParallelStrategy
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/strategies/__init__.py", line 15, in <module>
    from pytorch_lightning.strategies.bagua import BaguaStrategy  # noqa: F401
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/strategies/bagua.py", line 30, in <module>
    from pytorch_lightning.strategies.ddp import DDPStrategy
  File "/home/ubuntu/projects/txt2img/instruct-pix2pix/venv38/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 65, in <module>
    from torch.distributed.algorithms.model_averaging.averagers import ModelAverager
ModuleNotFoundError: No module named 'torch.distributed.algorithms.model_averaging'`

**Comment by holynski** [comment]
Looks like maybe the wrong version of PyTorch?

Did you install by using the environment.yaml file? What version of PyTorch did it install?

**Comment by holynski** [comment]
Closing stale issue. Feel free to comment further.
