### ISSUE TITLE
 instruct-pix2pix - Error loading script

### ISSUE THREAD

**Issue by Vizzarto** [timothybrooks/instruct-pix2pix#55]
I installed the extension, but after restarting auto 1111 I get this error:

Error loading script: instruct-pix2pix.py
Traceback (most recent call last):
  File "E:\MyProject\A.I\StableDiffusion\SD 2.0 install\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "E:\MyProject\A.I\StableDiffusion\SD 2.0 install\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "E:\MyProject\A.I\StableDiffusion\SD 2.0 install\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 24, in <module>
    from modules.ui_common import create_output_panel
ModuleNotFoundError: No module named 'modules.ui_common'

Сan someone tell me what to do? Maybe reinstall all over?

**Comment by holynski** [comment]
Not sure. Maybe worth creating an issue on the A1111 repo.
